wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1703824853.384723
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.13.6
      8:
      - 1
      - 2
      - 5
colsample_bytree:
  desc: null
  value: 0.37069896654761675
learning_rate:
  desc: null
  value: 0.13161203870319035
max_depth:
  desc: null
  value: 4.0
n_estimators:
  desc: null
  value: 635.0
subsample:
  desc: null
  value: 0.7337059149664782
